import { useEffect, useState } from 'react';
import { ActivityIndicator, Modal, Pressable, RefreshControl, ScrollView, View } from 'react-native';
import { dismissNotification, getActivities, getNotificationPreferences, getNotifications, markAllNotificationsRead, markNotificationRead, updateNotificationPreferences } from '../api/client';
import { AppText, Card, EmptyState, IconButton, PrimaryButton, Toggle } from '../components/ui';
import { colors } from '../styles/theme';
import { styles } from '../styles/styles';
import { Activity, Notification, NotificationPreference } from '../types/api';
import { getErrorMessage } from '../utils/errors';
import { activityTypeLabel, formatRelativeDate, notificationSeverityColor } from '../utils/notifications';

type Tab = 'notifications' | 'activities';
export function NotificationCenterScreen({ onClose, onUnreadChanged, token }: { onClose: () => void; onUnreadChanged: () => Promise<void>; token: string }) {
  const [tab, setTab] = useState<Tab>('notifications'); const [notifications, setNotifications] = useState<Notification[]>([]); const [activities, setActivities] = useState<Activity[]>([]); const [notificationCursor, setNotificationCursor] = useState<string | null>(null); const [activityCursor, setActivityCursor] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState<string | null>(null); const [preferencesVisible, setPreferencesVisible] = useState(false);
  async function load(reset = true) { setError(null); reset ? setLoading(true) : setRefreshing(true); try { if (tab === 'notifications') { const page = await getNotifications(token, { limit: 30, cursor: reset ? undefined : notificationCursor ?? undefined }); setNotifications((items) => reset ? page.items : [...items, ...page.items]); setNotificationCursor(page.nextCursor); } else { const page = await getActivities(token, { limit: 30, cursor: reset ? undefined : activityCursor ?? undefined }); setActivities((items) => reset ? page.items : [...items, ...page.items]); setActivityCursor(page.nextCursor); } } catch (cause) { setError(getErrorMessage(cause)); } finally { setLoading(false); setRefreshing(false); } }
  useEffect(() => { load(true); }, [tab, token]);
  async function read(item: Notification) { await markNotificationRead(token, item.id); setNotifications((items) => items.map((current) => current.id === item.id ? { ...current, readAt: current.readAt ?? new Date().toISOString() } : current)); await onUnreadChanged(); }
  async function dismiss(item: Notification) { await dismissNotification(token, item.id); setNotifications((items) => items.filter((current) => current.id !== item.id)); await onUnreadChanged(); await load(true); }
  async function readAll() { await markAllNotificationsRead(token); setNotifications((items) => items.map((item) => ({ ...item, readAt: item.readAt ?? new Date().toISOString() }))); await onUnreadChanged(); await load(true); }
  const items = tab === 'notifications' ? notifications : activities; const cursor = tab === 'notifications' ? notificationCursor : activityCursor;
  return <View style={styles.screen}><View style={styles.header}><IconButton name="arrow-back" onPress={onClose} /><AppText size="title" weight="bold">Central</AppText><IconButton name="settings-outline" onPress={() => setPreferencesVisible(true)} /></View><View style={styles.segmentedControl}><TabButton active={tab === 'notifications'} label="Notificações" onPress={() => setTab('notifications')} /><TabButton active={tab === 'activities'} label="Atividades" onPress={() => setTab('activities')} /></View>{tab === 'notifications' ? <Pressable onPress={readAll} style={styles.inlineAction}><AppText mono size="caption" style={{ color: colors.primary }}>Marcar todas como lidas</AppText></Pressable> : null}<ScrollView contentContainerStyle={styles.scrollContent} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => load(true)} tintColor={colors.primary} />}>{loading && !items.length ? <ActivityIndicator color={colors.primary} /> : null}{error ? <><EmptyState icon="cloud-offline-outline" title="Não foi possível carregar" message={error} /><PrimaryButton label="Tentar novamente" onPress={() => load(true)} /></> : null}{!loading && !error && !items.length ? <EmptyState icon={tab === 'notifications' ? 'notifications-off-outline' : 'time-outline'} title={tab === 'notifications' ? 'Sem notificações' : 'Sem atividades'} message={tab === 'notifications' ? 'Você está em dia.' : 'As ações aparecerão aqui.'} /> : null}{tab === 'notifications' ? notifications.map((item) => <NotificationRow key={item.id} item={item} onDismiss={() => dismiss(item)} onRead={() => read(item)} />) : activities.map((item) => <ActivityRow key={item.id} item={item} />)}{cursor ? <PrimaryButton label="Carregar mais" isLoading={refreshing} onPress={() => load(false)} tone="ghost" /> : null}</ScrollView><PreferencesModal onClose={() => setPreferencesVisible(false)} token={token} visible={preferencesVisible} /></View>;
}
function TabButton({ active, label, onPress }: { active: boolean; label: string; onPress: () => void }) { return <Pressable onPress={onPress} style={[styles.segmentedItem, active && styles.segmentedItemActive]}><AppText mono size="caption" style={{ color: active ? colors.primary : colors.muted }}>{label}</AppText></Pressable>; }
function NotificationRow({ item, onDismiss, onRead }: { item: Notification; onDismiss: () => void; onRead: () => void }) { return <Card style={[styles.notificationRow, item.readAt ? {} : styles.notificationUnread]}><View style={styles.row}><View style={[styles.notificationDot, { backgroundColor: notificationSeverityColor(item) }]} /><View style={styles.listText}><AppText weight="bold">{item.title}</AppText><AppText muted size="caption">{item.message}</AppText><AppText mono muted size="caption">{formatRelativeDate(item.createdAt)}</AppText></View></View><View style={styles.actionRow}>{!item.readAt ? <IconButton name="checkmark" size={18} onPress={onRead} /> : null}<IconButton color={colors.danger} name="close" size={18} onPress={onDismiss} /></View></Card>; }
function ActivityRow({ item }: { item: Activity }) { const effective = typeof item.metadata?.effectiveDate === 'string' ? item.metadata.effectiveDate : null; return <Card><AppText weight="bold">{item.title}</AppText>{item.description ? <AppText muted size="caption">{item.description}</AppText> : null}<AppText mono muted size="caption">{activityTypeLabel(item.type)} · {formatRelativeDate(item.occurredAt)}</AppText>{effective ? <AppText mono muted size="caption">Data efetiva: {new Date(effective).toLocaleDateString('pt-BR')}</AppText> : null}</Card>; }
function PreferencesModal({ onClose, token, visible }: { onClose: () => void; token: string; visible: boolean }) { const [items, setItems] = useState<NotificationPreference[]>([]); const [original, setOriginal] = useState<NotificationPreference[]>([]); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); useEffect(() => { if (!visible) return; setLoading(true); setError(null); getNotificationPreferences(token).then(({ preferences }) => { setItems(preferences); setOriginal(preferences); }).catch((cause) => setError(getErrorMessage(cause))).finally(() => setLoading(false)); }, [token, visible]); const update = (category: NotificationPreference['category'], changes: Partial<NotificationPreference>) => setItems((values) => values.map((item) => item.category === category ? { ...item, ...changes } : item)); const save = async () => { setSaving(true); setError(null); try { await updateNotificationPreferences(token, items); onClose(); } catch (cause) { setError(getErrorMessage(cause)); } finally { setSaving(false); } }; return <Modal animationType="slide" transparent visible={visible} onRequestClose={() => { setItems(original); onClose(); }}><View style={styles.modalBackdrop}><View style={styles.modalPanel}><View style={styles.sectionHeader}><AppText size="title" weight="bold">Preferências</AppText><IconButton name="close" onPress={() => { setItems(original); onClose(); }} /></View>{loading ? <ActivityIndicator color={colors.primary} /> : items.map((item) => <View key={item.category} style={styles.preferenceRow}><View style={styles.listText}><AppText weight="semibold">{({ invoices: 'Faturas', events: 'Eventos', subscriptions: 'Assinaturas', budgets: 'Orçamentos', goals: 'Metas' } as Record<string, string>)[item.category]}</AppText>{item.category !== 'budgets' ? <View style={styles.row}><IconButton name="remove" size={16} onPress={() => update(item.category, { leadDays: Math.max(0, (item.leadDays ?? 0) - 1) })} /><AppText mono size="caption">{item.leadDays ?? 0} dias</AppText><IconButton name="add" size={16} onPress={() => update(item.category, { leadDays: Math.min(90, (item.leadDays ?? 0) + 1) })} /></View> : <AppText muted size="caption">Sem antecedência</AppText>}</View><Toggle isActive={item.enabled} onToggle={() => update(item.category, { enabled: !item.enabled })} /></View>)}{error ? <AppText style={styles.valueDanger}>{error}</AppText> : null}<PrimaryButton label="Salvar alterações" isLoading={saving} onPress={save} /></View></View></Modal>; }
