import { StyleSheet } from 'react-native';

import { colors, fonts, radius, shadows, spacing } from './theme';

export const styles = StyleSheet.create({
  actionRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
  },
  appContainer: {
    backgroundColor: colors.background,
    flex: 1,
  },
  avatar: {
    alignItems: 'center',
    backgroundColor: colors.cardHigh,
    borderColor: colors.borderMuted,
    borderRadius: radius.pill,
    borderWidth: 1,
    height: 40,
    justifyContent: 'center',
    overflow: 'hidden',
    width: 40,
  },
  avatarLarge: {
    height: 96,
    width: 96,
  },
  bottomNav: {
    alignItems: 'center',
    backgroundColor: colors.cardLow,
    borderColor: colors.borderMuted,
    borderTopLeftRadius: radius.md,
    borderTopRightRadius: radius.md,
    borderTopWidth: 1,
    bottom: 0,
    flexDirection: 'row',
    height: 70,
    justifyContent: 'space-around',
    left: 0,
    paddingBottom: spacing.xs,
    paddingHorizontal: spacing.xs,
    position: 'absolute',
    right: 0,
    ...shadows.panel,
  },
  bottomNavItem: {
    alignItems: 'center',
    borderRadius: radius.pill,
    gap: 2,
    justifyContent: 'center',
    minHeight: 52,
    minWidth: 62,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  bottomNavItemActive: {
    backgroundColor: colors.primaryDim,
    minWidth: 88,
  },
  bottomNavLabel: {
    color: colors.muted,
    fontFamily: fonts.mono,
    fontSize: 10,
    lineHeight: 14,
  },
  bottomNavLabelActive: {
    color: colors.onPrimary,
  },
  card: {
    backgroundColor: colors.cardElevated,
    borderColor: colors.border,
    borderRadius: radius.lg,
    borderWidth: 1,
    padding: spacing.md,
    ...shadows.panel,
  },
  cardGlow: {
    borderColor: '#3b5a68',
  },
  centered: {
    alignItems: 'center',
    backgroundColor: colors.background,
    flex: 1,
    justifyContent: 'center',
  },
  centerText: {
    textAlign: 'center',
  },
  chip: {
    alignItems: 'center',
    backgroundColor: colors.cardHigh,
    borderColor: colors.borderMuted,
    borderRadius: radius.pill,
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacing.xs,
    minHeight: 38,
    paddingHorizontal: spacing.md,
  },
  chipActive: {
    backgroundColor: colors.primaryMuted,
    borderColor: colors.primary,
  },
  chipDanger: {
    backgroundColor: colors.dangerContainer,
    borderColor: colors.danger,
  },
  chipTelegram: {
    backgroundColor: '#123149',
    borderColor: '#1d6d9c',
  },
  chipText: {
    color: colors.muted,
    fontFamily: fonts.mono,
    fontSize: 12,
  },
  compactCardGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
  },
  container: {
    backgroundColor: colors.background,
    flex: 1,
  },
  content: {
    flex: 1,
    gap: spacing.lg,
    padding: spacing.md,
  },
  dangerButton: {
    backgroundColor: colors.dangerContainer,
    borderColor: colors.danger,
  },
  dangerButtonText: {
    color: colors.danger,
  },
  dateGroup: {
    color: colors.muted,
    fontFamily: fonts.mono,
    fontSize: 12,
    letterSpacing: 1.2,
    marginTop: spacing.md,
    textTransform: 'uppercase',
  },
  disabledButton: {
    opacity: 0.65,
  },
  emptyIcon: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: colors.primaryMuted,
    borderColor: colors.primary,
    borderRadius: radius.pill,
    borderWidth: 1,
    height: 56,
    justifyContent: 'center',
    width: 56,
  },
  emptyState: {
    alignItems: 'center',
    gap: spacing.sm,
    padding: spacing.lg,
  },
  fab: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: radius.lg,
    bottom: 86,
    height: 58,
    justifyContent: 'center',
    position: 'absolute',
    right: spacing.lg,
    width: 58,
    zIndex: 20,
    ...shadows.glow,
  },
  fieldRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  form: {
    flex: 1,
  },
  formField: {
    gap: spacing.sm,
  },
  formLabel: {
    color: colors.muted,
    fontFamily: fonts.mono,
    fontSize: 12,
    letterSpacing: 0.8,
  },
  ghostButton: {
    backgroundColor: colors.transparent,
    borderColor: colors.primary,
  },
  ghostButtonText: {
    color: colors.primary,
  },
  header: {
    alignItems: 'center',
    backgroundColor: colors.background,
    borderBottomColor: colors.borderMuted,
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  heroCard: {
    gap: spacing.md,
    minHeight: 164,
    overflow: 'hidden',
    padding: spacing.lg,
  },
  iconButton: {
    alignItems: 'center',
    backgroundColor: colors.cardLow,
    borderRadius: radius.pill,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  inlineAction: {
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  inlineActionText: {
    color: colors.primary,
    fontFamily: fonts.mono,
    fontSize: 12,
  },
  input: {
    color: colors.text,
    flex: 1,
    fontFamily: fonts.body,
    fontSize: 16,
    minHeight: 48,
    padding: 0,
  },
  inputShell: {
    alignItems: 'center',
    backgroundColor: colors.cardLowest,
    borderColor: colors.borderMuted,
    borderRadius: radius.md,
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacing.sm,
    minHeight: 54,
    paddingHorizontal: spacing.md,
  },
  itemActions: {
    flexDirection: 'row',
    gap: spacing.xs,
  },
  itemTitle: {
    color: colors.text,
    fontFamily: fonts.semibold,
    fontSize: 16,
  },
  keyboardContent: {
    flexGrow: 1,
    justifyContent: 'center',
    padding: spacing.lg,
  },
  listItem: {
    alignItems: 'center',
    backgroundColor: colors.cardElevated,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacing.md,
    justifyContent: 'space-between',
    padding: spacing.md,
  },
  listText: {
    flex: 1,
    gap: spacing.xs,
  },
  loginCard: {
    gap: spacing.xl,
    padding: spacing.xl,
  },
  loginLogo: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: colors.cardHigh,
    borderColor: colors.border,
    borderRadius: radius.pill,
    borderWidth: 1,
    height: 82,
    justifyContent: 'center',
    width: 82,
  },
  metric: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  metricValue: {
    color: colors.text,
    fontFamily: fonts.bold,
    fontSize: 16,
  },
  modalBackdrop: {
    backgroundColor: 'rgba(6, 14, 32, 0.88)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalHandle: {
    alignSelf: 'center',
    backgroundColor: colors.border,
    borderRadius: radius.pill,
    height: 5,
    marginBottom: spacing.lg,
    width: 88,
  },
  modalPanel: {
    backgroundColor: colors.cardLow,
    borderColor: colors.border,
    borderTopLeftRadius: radius.xl,
    borderTopRightRadius: radius.xl,
    borderTopWidth: 1,
    maxHeight: '92%',
    padding: spacing.lg,
  },
  monthSelector: {
    alignItems: 'center',
    backgroundColor: colors.cardLow,
    borderColor: colors.borderMuted,
    borderRadius: radius.md,
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacing.xs,
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.xs,
  },
  muted: {
    color: colors.muted,
    fontFamily: fonts.body,
  },
  page: {
    flex: 1,
    paddingBottom: 70,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderColor: colors.primary,
    borderRadius: radius.md,
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacing.sm,
    justifyContent: 'center',
    minHeight: 52,
    paddingHorizontal: spacing.lg,
    ...shadows.glow,
  },
  primaryButtonText: {
    color: colors.onPrimary,
    fontFamily: fonts.mono,
    fontSize: 14,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  progressBar: {
    backgroundColor: colors.border,
    borderRadius: radius.pill,
    height: 8,
    overflow: 'hidden',
  },
  progressFill: {
    backgroundColor: colors.primary,
    borderRadius: radius.pill,
    height: '100%',
  },
  row: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
  },
  screen: {
    flex: 1,
  },
  scrollContent: {
    gap: spacing.lg,
    padding: spacing.md,
    paddingBottom: 104,
  },
  searchShell: {
    alignItems: 'center',
    backgroundColor: colors.cardLow,
    borderColor: colors.borderMuted,
    borderRadius: radius.md,
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacing.sm,
    minHeight: 48,
    paddingHorizontal: spacing.sm,
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sectionSubtitle: {
    color: colors.muted,
    fontFamily: fonts.body,
    fontSize: 15,
    lineHeight: 22,
  },
  sectionTitle: {
    color: colors.text,
    fontFamily: fonts.bold,
    fontSize: 24,
    lineHeight: 30,
  },
  segmentedControl: {
    backgroundColor: colors.cardLow,
    borderColor: colors.borderMuted,
    borderRadius: radius.md,
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacing.xs,
    padding: spacing.xs,
  },
  segmentedItem: {
    alignItems: 'center',
    borderRadius: radius.sm,
    flex: 1,
    flexDirection: 'row',
    gap: spacing.xs,
    justifyContent: 'center',
    minHeight: 44,
  },
  segmentedItemActive: {
    backgroundColor: colors.cardHigh,
  },
  segmentedItemDanger: {
    backgroundColor: colors.dangerContainer,
  },
  segmentedText: {
    color: colors.muted,
    fontFamily: fonts.mono,
    fontSize: 14,
  },
  statCard: {
    flexBasis: '47%',
    flexGrow: 1,
    gap: spacing.sm,
    minHeight: 82,
  },
  tab: {
    alignItems: 'center',
    borderColor: colors.borderMuted,
    borderRadius: radius.md,
    borderWidth: 1,
    minWidth: 110,
    padding: spacing.sm,
  },
  tabs: {
    gap: spacing.sm,
    padding: spacing.md,
  },
  text: {
    color: colors.text,
    fontFamily: fonts.body,
  },
  text_body: {
    fontSize: 16,
    lineHeight: 23,
  },
  text_bold: {
    fontFamily: fonts.bold,
  },
  text_caption: {
    fontSize: 12,
    lineHeight: 16,
  },
  text_display: {
    fontSize: 34,
    lineHeight: 42,
  },
  text_large: {
    fontSize: 18,
    lineHeight: 26,
  },
  text_mono: {
    fontFamily: fonts.mono,
  },
  text_muted: {
    color: colors.muted,
  },
  text_regular: {
    fontFamily: fonts.body,
  },
  text_semibold: {
    fontFamily: fonts.semibold,
  },
  text_title: {
    fontSize: 22,
    lineHeight: 28,
  },
  title: {
    color: colors.primary,
    fontFamily: fonts.bold,
    fontSize: 34,
    lineHeight: 40,
  },
  toggleThumb: {
    backgroundColor: colors.text,
    borderRadius: radius.pill,
    height: 22,
    transform: [{ translateX: 2 }],
    width: 22,
  },
  toggleThumbActive: {
    transform: [{ translateX: 24 }],
  },
  toggleTrack: {
    backgroundColor: colors.border,
    borderRadius: radius.pill,
    height: 26,
    justifyContent: 'center',
    width: 50,
  },
  toggleTrackActive: {
    backgroundColor: colors.primaryDim,
  },
  topBar: {
    alignItems: 'center',
    backgroundColor: colors.background,
    borderBottomColor: colors.borderMuted,
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 62,
    paddingHorizontal: spacing.md,
  },
  topBrand: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.sm,
  },
  transactionIcon: {
    alignItems: 'center',
    backgroundColor: colors.cardHigh,
    borderRadius: radius.pill,
    height: 50,
    justifyContent: 'center',
    width: 50,
  },
  watermark: {
    bottom: -28,
    opacity: 0.08,
    position: 'absolute',
    right: -18,
  },
  valueDanger: {
    color: colors.danger,
  },
  valuePrimary: {
    color: colors.primary,
  },
});
